version: '3'

volumes:
  node_modules:
  postgres:

services:
  app:
    image: node:16.13.2
    ports:
      - 3103:3103
      - 5658:5658
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
    working_dir: /workspace
    tty: true
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql.custom.conf:/workspace/postgresql.custom.conf
    ports:
      - 5536:5536
